MODEL:
  TYPE: shuffle
  NAME: shuffle_vit_tiny_patch4_window7_224_local7midV2
  DROP_PATH_RATE: 0.1
  SWIN:
    EMBED_DIM: 96
    DEPTHS: [ 2, 2, 6, 2 ]
    NUM_HEADS: [ 3, 6, 12, 24 ]
    WINDOW_SIZE: 7